version: 2
updates:
- package-ecosystem: npm
  directory: "/crawl-cli"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - automerge
  ignore:
  - dependency-name: npm
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: puppeteer
    versions:
    - 7.0.1
    - 7.0.4
    - 7.1.0
